name: ci

concurrency:
  cancel-in-progress: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
  group: ci-${{ github.ref_name }}-${{ github.event_name }}

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build-server:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Build docker
        uses: meysam81/build-docker@main
        with:
          context: ./server
          image-extra-tags: |
            ghcr.io/${{ github.repository }}/ente-server:${{ github.event.repository.pushed_at }}
            ghcr.io/${{ github.repository }}/ente-server:${{ github.run_id }}
            ghcr.io/${{ github.repository }}/ente-server:latest
          image-name: ghcr.io/${{ github.repository }}/ente-server
          kubescape: true
          kubescape-upload-sarif: true
          repository: ente-io/ente
